---
- name: Configure Windows settings
  hosts: all
  gather_facts: no

  vars_prompt:
    - name: admin_password
      prompt: "Enter the password for the Administrator account"
      private: yes
    - name: ansible_user
      prompt: "Enter the username for the Ansible connection"
      private: no
    - name: ansible_password
      prompt: "Enter the password for the Ansible connection"
      private: yes
#    - name: new_computer_name
 #     prompt: "Enter new computer name"
  #    private: no

  tasks:
    - name: Create Temp directory on remote host
      win_file:
        path: C:\Temp
        state: directory  # Создаем директорию

    - name: Copy PowerShell script to configure Administrator
      win_copy:
        content: |
          # Устанавливаем пароль для учетной записи "Administrator"
          $password = ConvertTo-SecureString '{{ admin_password }}' -AsPlainText -Force
          Set-LocalUser -Name Administrator -Password $password
          # Активируем учетную запись "Administrator"
          Enable-LocalUser -Name Administrator
        dest: C:\Temp\configure_admin.ps1

    - name: Run PowerShell script to configure Administrator
      win_shell: powershell.exe -ExecutionPolicy ByPass -File C:\Temp\configure_admin.ps1

    - name: Copy PowerShell script to change computer name
      win_copy:
        src: /mnt/d/Scripts/etuconf.ps1
        dest: C:\Temp\new_pc.ps1
        force: yes

    - name: Run Script
      win_shell: powershell.exe -ExecutionPolicy ByPass -File C:\Temp\new_pc.ps1
#
 #   - name: Run PowerShell script to change computer name
  #    win_shell: Rename-Computer -NewName "{{ new_computer_name }}" -Force -Restart
   #   when: new_computer_name != ""

    - name: Wait for host to reboot
      wait_for_connection:
        delay: 10  # Периодичность проверки подключения после перезагрузки (в секундах)
        timeout: 300  # Время ожидания подключения после перезагрузки (в секундах), в данном случае 5 минут
      become: no

    - name: Delete C:\Temp
      win_file:
        path: C:\Temp
        state: absent
